name: Build Workflow

on:
  push:
    branches:
      - main
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v6

      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      - name: Install requirements
        run: |
          pip install pyinstaller pygame psutil pyperclip keyboard
      
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "neko"  "neko.pyw"
      
      - name: Copy config files
        run: |
          copy *.json dist\neko
      
      - name: Upload artifacts 
        uses: actions/upload-artifact@v7
        with:
          name: neko
          path: dist/neko
